### ISSUE TITLE
KeyError: 'lms' when get test outcome using the pretrained models?

### ISSUE THREAD

**Issue by codgodtao** [liangjiandeng/DLPan-Toolbox#1]
I want to open 01-DL-toolbox(Pytorch)/UDL/pansharpening and run run_test_pansharpening.py for testing.
However, when testing with the dataset you provided(NY1_WV3_RR.mat), an error occurred ,please kindly take a look at what causes this and how to solve it.

The details of the error are shown as follows

```
import sys
sys.path.append('../..')
from UDL.AutoDL import TaskDispatcher
from UDL.AutoDL.trainer import main
if __name__ == '__main__':
    cfg = TaskDispatcher.new(task='pansharpening', mode='entrypoint', arch='MSDCNN')
    cfg.resume_from = "UDL/pretrained-model/WV3/msdcnn.pth"
    cfg.eval = True
    cfg.workflow = [('val', 1)]
    print(TaskDispatcher._task.keys())
    main(cfg)
```

loading SingleDataset: **['../Data/pansharpening/WV3/test_data/NY1_WV3_RR.mat'] with 2047.0**
Hooks will be executed in the following order:
...
Traceback (most recent call last):
  File "DLPan-Toolbox-main\DLPan-Toolbox-main\01-DL-toolbox(Pytorch)\UDL\pansharpening\run_test_pansharpening.py", line 18, in <module>
    main(cfg)
  File "DLPan-Toolbox-main\DLPan-Toolbox-main\01-DL-toolbox(Pytorch)\UDL\AutoDL\trainer.py", line 257, in main
    trainer(
  File "DLPan-Toolbox-main\DLPan-Toolbox-main\01-DL-toolbox(Pytorch)\UDL\AutoDL\trainer.py", line 228, in trainer
    runner.run(data_loaders, cfg.workflow)
  File "DLPan-Toolbox-main\DLPan-Toolbox-main\01-DL-toolbox(Pytorch)\UDL\pansharpening\../mmcv\mmcv\runner\epoch_based_runner.py", line 238, in run
    epoch_runner(data_loaders[mode], **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "DLPan-Toolbox-main\DLPan-Toolbox-main\01-DL-toolbox(Pytorch)\UDL\pansharpening\../mmcv\mmcv\runner\epoch_based_runner.py", line 165, in val
    for i, data_batch in enumerate(self.data_loader):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 652, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1373, in _process_data
    data.reraise()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\_utils.py", line 461, in reraise
    raise exception
**KeyError: Caught KeyError in DataLoader worker process 0.**
Original Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "DLPan-Toolbox-main\DLPan-Toolbox-main\01-DL-toolbox(Pytorch)\UDL\pansharpening\evaluation\ps_evaluate.py", line 216, in __getitem__
    test_lms, test_mms, test_ms, test_pan, gt = self.dataset(file_path, self.img_scale)
  **File "DLPan-Toolbox-main\DLPan-Toolbox-main\01-DL-toolbox(Pytorch)\UDL\pansharpening\evaluation\ps_evaluate.py", line 63, in load_dataset_singlemat
    lms = torch.from_numpy(data['lms'] / scale).permute(2, 0, 1)  # CxHxW = 8x256x256
KeyError: 'lms'**
`

**Comment by XiaoXiao-Woo** [comment]
Thank you for your advise. I have updated the code.

**Comment by codgodtao** [comment]
Thank you very much. The problem is solved!
