### ISSUE TITLE
添加项目

### ISSUE THREAD

**Issue by songwenhao123** [liangjiandeng/DLPan-Toolbox#11]
您好，我按照您readme中的步骤添加项目后，运行报错，您可以帮助解决一下吗？十分感谢
Traceback (most recent call last):
  File "run_pansharpening.py", line 16, in <module>
    main(cfg)
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../../UDL/AutoDL/trainer.py", line 256, in main
    trainer(
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../../UDL/AutoDL/trainer.py", line 227, in trainer
    runner.run(data_loaders, cfg.workflow)
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../mmcv/mmcv/runner/epoch_based_runner.py", line 238, in run
    epoch_runner(data_loaders[mode], **kwargs)
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../mmcv/mmcv/runner/epoch_based_runner.py", line 75, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../mmcv/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../../UDL/Basis/python_sub_class.py", line 209, in train_step
    loss_dict = self.model.train_step(args[0], **kwargs)
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../mmcv/mmcv/parallel/data_parallel.py", line 78, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/wenhao/installs/conda/envs/PanCollection/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPPNN' object has no attribute 'train_step'

**Comment by XiaoXiao-Woo** [comment]
Please refer to the existing model to add functions "train_step" and "val_step".

**Comment by XiaoXiao-Woo** [comment]
Please refer to the existing model to add functions "train_step" and
"val_step".

songwenhao123 ***@***.***> 于2023年4月8日周六 10:26写道：

**Comment by songwenhao123** [comment]
非常感谢您的解答，我已经解决了这个问题，还有一个问题想要请教一下，希望您可以帮助我，十分感谢
- Checkpoints will be saved to /home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/results/pansharpening/wv3/panformer/Test/model_2023-04-08-20-29-40
Traceback (most recent call last):
  File "run_pansharpening.py", line 16, in <module>
    main(cfg)
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../../UDL/AutoDL/trainer.py", line 256, in main
    trainer(
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../../UDL/AutoDL/trainer.py", line 227, in trainer
    runner.run(data_loaders, cfg.workflow)
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../mmcv/mmcv/runner/epoch_based_runner.py", line 238, in run
    epoch_runner(data_loaders[mode], **kwargs)
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../mmcv/mmcv/runner/epoch_based_runner.py", line 75, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../mmcv/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../../UDL/Basis/python_sub_class.py", line 209, in train_step
    loss_dict = self.model.train_step(args[0], **kwargs)
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../mmcv/mmcv/parallel/data_parallel.py", line 78, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/pansharpening/../../UDL/pansharpening/models/Panformer/model_panformer.py", line 331, in train_step
    loss = self.criterion(sr, gt, *args, **kwargs)
  File "/home/wenhao/installs/conda/envs/PanCollection/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GPPNN' object has no attribute 'criterion'

**Comment by songwenhao123** [comment]
非常感谢您的回答，我还有一个问题想请教一下，为什么我使用您提供的数据集训练之后，得到的模型测试结果很差。
test time: 47.02578783035278
- Epoch(val) [1][1080]  SAM: 46.33373, ERGAS: 139.27152, PSNR: 4.19697
- Training time 0:00:50
下面是我训练的设置
import argparse
import os

from UDL.AutoDL import TaskDispatcher


class parser_args(TaskDispatcher, name='BDPN'):
    def __init__(self, cfg=None):
        super(parser_args, self).__init__()
        if cfg is None:
            from UDL.Basis.option import panshaprening_cfg
            cfg = panshaprening_cfg()

        script_path = os.path.dirname(os.path.dirname(__file__))
        root_dir = script_path.split(cfg.task)[0]

        # model_path = f'{root_dir}/results/{cfg.task}/wv3/BDPN/Test/.pth.tar'
        model_path = f'/home/wenhao/Remot/PanCollection/01-DL-toolbox/UDL/results/pansharpening/wv3/BDPN/Test/model_2023-04-07-22-01-48/model_best_.pth'

        parser = argparse.ArgumentParser(description='PyTorch Pansharpening Training')
        # * Logger
        parser.add_argument('--out_dir', metavar='DIR', default=f'{root_dir}/results/{cfg.task}',
                            help='path to save model')
        # * Training
        parser.add_argument('--lr', default=0.0001, type=float)  # 1e-4 2e-4 8
        parser.add_argument('--lr_scheduler', default=True, type=bool)
        parser.add_argument('--samples_per_gpu', default=8, type=int,  # 8
                            metavar='N', help='mini-batch size (default: 256)')
        parser.add_argument('--print-freq', '-p', default=50, type=int,
                            metavar='N', help='print frequency (default: 10)')
        parser.add_argument('--epochs', default=1000, type=int)
        parser.add_argument('--workers_per_gpu', default=0, type=int)
        parser.add_argument('--resume_from',
                            default=model_path,
                            type=str, metavar='PATH',
                            help='path to latest checkpoint (default: none)')
        # * Model and Dataset
        parser.add_argument('--arch', '-a', metavar='ARCH', default='BDPN', type=str,
                            choices=['PanNet', 'DiCNN', 'PNN', 'FusionNet'])
        parser.add_argument('--dataset', default={'train': 'wv3', 'val': 'valid_wv3'}, type=str,
                            choices=[None, 'wv2', 'wv3', 'wv4', 'qb',
                                     'TestData_qb', 'TestData_wv2', 'TestData_wv3', 'TestData_wv4',
                                     'San_Francisco_QB_RR', 'San_Francisco_QB_FR', 'NY1_WV3_FR',
                                     'NY1_WV3_RR', 'Alice_WV4_FR', 'Alice_WV4_RR', 'Rio_WV2_FR', 'Rio_WV2_RR','test_wv3_multiExm1'],
                            help="training choices: ['wv2', 'wv3', 'wv4', 'qb'],"
                                 "validation choices: ['valid_wv2_10000','valid_wv3_10000', 'valid_wv4_10000', 'valid_qb_10000']"
                                 "test choices is ['TestData_wv2', 'TestData_wv3', 'TestData_wv4', 'TestData_qb'], and others with RR/FR")
        parser.add_argument('--eval', default=False, type=bool,
                            help="performing evalution for patch2entire")

        args = parser.parse_args()
        args.start_epoch = args.best_epoch = 1
        args.experimental_desc = "Test"
        # cfg.save_fmt = 'tif'
        cfg.img_range = 2047.0

        cfg.merge_args2cfg(args)
        print(cfg.pretty_text)
        # cfg.workflow = [('train', 50), ('val', 1)]
        cfg.workflow = [('val', 1)]  # only val workflow means perform test.
        # cfg.workflow = [('train', 50)]
        # cfg.dataset = {'train': 'wv3', 'val': 'valid_wv3'}
        self.merge_from_dict(cfg)

**Comment by songwenhao123** [comment]
我在测试的时候发现您提供的数据集中lms: torch.Size([20, 8, 256, 256]), ms: torch.Size([20, 8, 64, 64]), pan: torch.Size([20, 1, 256, 256]), gt: torch.Size([20, 256, 256, 8])，gt为什么和其他的不太一样，是否存在问题？希望您能解答

**Comment by liangjiandeng** [comment]
为方便matlab测试传统方法，我们的gt是NxHxWxC格式的（即[20, 256, 256, 8]），请用permute命令将你的结果维度从NxCxHxW（即[20, 8, 256, 256]）转为NxHxWxC（即[20, 256, 256, 8]），即可进行计算指标。请详细阅读toolbox文档+matlab包文件。

**Comment by songwenhao123** [comment]
谢谢您的回答，我还想请问一下，我想给项目添加损失函数的时候，应该在何处更改？
